server:
  port: 80
spring:
  application:
    name: consumer-order-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhouhao_sql?useUnicode=true?characterEncoding=utf-8&useSSL=false
    username: root
    password: 19990302

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true