server:
  port: 80

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    #指定feign日志监控的接口
    com.zhouhao.springcloud.service.PaymentFeignService: debug

