server:
  port: 8004
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhouhao_sql?useUnicode=true?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: localhost:2181


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhouhao.springcloud.entity